### ISSUE TITLE
Fails to compile on latest crystal 0.31.0

### ISSUE THREAD

**Issue by bararchy** [stumpycr/pcf-parser#1]
This is a dependency of "stumpy core" and as such it fails any use of stumpy_png
```crystal
In lib/pcf-parser/src/pcf-parser.cr:197:15

 197 | @bytes[index] & (1 << (7 - (x % 8))) != 0
             ^
Error: no overload matches 'Slice(UInt8)#[]' with type Float64

Overloads are:
 - Slice(T)#[](start : Int, count : Int)
 - Slice(T)#[](range : Range)
 - Indexable(T)#[](index : Int)
```

**Comment by l3kn** [comment]
Neither stumpy_core nor stumpy_png should depend on this, can you take a look at your projects `shard.lock`? Maybe it was required by an older version of some shard.

I've made a few changes to the code, can you check if you are still getting errors with the new verisons?

**Comment by bararchy** [comment]
My bad, I meant: https://github.com/stumpycr/stumpy_utils which uses it in the shards.yml file :)
